---
name: Create Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read

jobs:
  release:

    permissions:
      contents: write

    uses: project-cdim/.github/.github/workflows/create-release.yml@main
